# Generated by Django 6.0.3 on 2026-03-19 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id_plantilla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('VIDEO', 'Video'), ('IMAGEN', 'Imagen'), ('AUDIO', 'Audio'), ('METADATO', 'Metadato'), ('DOCUMENTO', 'Documento')], max_length=10)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('ruta_base', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plantilla',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('PROPUESTO', 'Propuesto'), ('ANALISIS', 'Análisis'), ('APROVADO', 'Aprobado'), ('PLANIFICACION', 'Planificación'), ('EJECUCION', 'Ejecución'), ('SEGUIMIENTO', 'Seguimiento'), ('PAUSADO', 'Pausado'), ('CANCELADO', 'Cancelado'), ('COMPLETADO', 'Completado'), ('CERRADO', 'Cerrado')], default='PROPUESTO', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_cliente', models.ForeignKey(db_column='id cliente', on_delete=django.db.models.deletion.CASCADE, to='VitrioApp.cliente')),
            ],
            options={
                'db_table': 'proyecto',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('resolucion', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SIN_CONEXION', 'Sin Conexión')], default='Activo', max_length=15)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.CASCADE, to='VitrioApp.proyecto')),
            ],
            options={
                'db_table': 'dispositivo',
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('ruta', models.CharField(max_length=500)),
                ('tipo', models.CharField(choices=[('VIDEO', 'Video'), ('IMAGEN', 'Imagen'), ('AUDIO', 'Audio'), ('PAQUETE', 'Paquete'), ('METADATO', 'Metadato'), ('DOCUMENTO', 'Documento')], max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_plantilla', models.ForeignKey(blank=True, db_column='id_plantilla', null=True, on_delete=django.db.models.deletion.SET_NULL, to='VitrioApp.plantilla')),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.CASCADE, to='VitrioApp.proyecto')),
            ],
            options={
                'db_table': 'archivo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_naciemiento', models.DateField(blank=True, null=True)),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador '), ('ADMINISTRADOR_CLIENTE', 'Administrador Cliente'), ('USUARIO', 'Usuario')], max_length=25)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='VitrioApp.cliente')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id_credencial', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='VitrioApp.usuario')),
            ],
            options={
                'db_table': 'credencial',
            },
        ),
    ]
